name: post to ui_component
on:
  push:
    branches: 
      - master
 
jobs:
  hi:
    name: Hi
    runs-on: ubuntu-latest
    steps:
    - name: Check out code
      uses: actions/checkout@v1
    - name: Slack Notification
      if: always()
      uses: rtCamp/action-slack-notify@master
      env:
        SLACK_CHANNEL: sandbox
        SLACK_MESSAGE: 'おはよう'
        SLACK_TITLE: 'タイトル'
        SLACK_USERNAME: 'bot from matzz'
        SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
